spring:
  application:
    name: sentiment-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/sentiment_db
    username: hackathon
    password: hackathon2024
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# URL del servicio ML
ml:
  service:
    url: http://localhost:8000

logging:
  level:
    com.hackathon: DEBUG
    org.springframework.web: INFO
